### ISSUE TITLE
Modules are not in a shared workspace

### ISSUE THREAD

**Issue by jpodivin** [openstack-k8s-operators/lib-common#229]
Repo could use workspace to handle multiple modules. Workspaces were introduced in go 1.18 for use cases just like this one.[0]

[0]https://go.dev/blog/get-familiar-with-workspaces

**Comment by jpodivin** [comment]
I see. And why isn't it checked in?

**Comment by stuggi** [comment]
> I see. And why isn't it checked in?

the main reason is that we have not checked it in, is that the downstream build process for the operators does not support it and fail with the files in place. to keep all the repos in sync, we also don't have it here.

**Comment by jpodivin** [comment]
> > I see. And why isn't it checked in?
> 
> the main reason is that we have not checked it in, is that the downstream build process for the operators does not support it and fail with the files in place. to keep all the repos in sync, we also don't have it here.

That does indeed make sense. Closing the issue.
